/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.42.0.0
 *
 * Project: 'blinky' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* ARM::CMSIS-View:Event Recorder&DAP@1.6.0 */
#define RTE_CMSIS_View_EventRecorder
#define RTE_CMSIS_View_EventRecorder_DAP
/* ARM::CMSIS-View:Fault:Record@1.1.0 */
#define RTE_CMSIS_View_Fault_Record
/* ARM::CMSIS-View:Fault:Storage@1.1.0 */
#define RTE_CMSIS_View_Fault_Storage
/* ARM::CMSIS:RTOS2:FreeRTOS&Cortex-M@11.2.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_FreeRTOS        /* CMSIS-RTOS2 FreeRTOS */
/* ARM::RTOS&FreeRTOS:Config&CMSIS RTOS2@11.2.0 */
#define RTE_RTOS_FreeRTOS_CONFIG_RTOS2  /* RTOS FreeRTOS Config for CMSIS RTOS2 API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@11.2.0 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Event Groups@11.2.0 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS   /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_4@11.2.0 */
#define RTE_RTOS_FreeRTOS_HEAP_4        /* RTOS FreeRTOS Heap 4 */
/* ARM::RTOS&FreeRTOS:Timers@11.2.0 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* Keil::CMSIS Driver:GPIO@1.2.0 */
#define RTE_Drivers_GPIO0               /* Driver GPIO0 */
/* Keil::CMSIS-Compiler:File Interface:MDK-MW File System@1.0.1 */
#define RTE_CMSIS_Compiler_File_Interface        /* CMSIS-Compiler File Interface */
#define RTE_CMSIS_Compiler_File_Interface_MDK_MW /* CMSIS-Compiler File Interface: MDK-Middleware File System */
/* Keil::Device:CubeMX@1.0.0 */
#define RTE_DEVICE_CUBE_MX
#define CMSIS_device_header "stm32f4xx.h"
/* Keil::File System&MDK:CORE@8.0.2 */
#define RTE_FileSystem_Core             /* File System Core */
/* Keil::File System&MDK:Drive:RAM@8.0.2 */
#define RTE_FileSystem_Drive_RAM_0      /* File System RAM Drive 0 */



#endif /* RTE_COMPONENTS_H */
